// ACTION TYPES

const CREATE_POST = 'CREATE_POST'
const READ_POST = 'READ_POST'
const UPDATE_POST = 'UPDATE_POST'
const DELETE_POST = 'DELETE_POST'

// INITIAL STATE
const initialPosts = []

// ACTION CREATORS

// THUNK CREATORS

// REDUCER
